name: proxy_rsshub
on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    tags:
      - "test-*"
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-20.04
    container: node:16.16.0
    env:
      TZ: Asia/Shanghai # https://xirikm.net/2020/215-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # Checking out the repo
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set Python
        run: |
          echo "python=/usr/bin/python3.9" >> $GITHUB_ENV  
      - name: Install Python 3.9
        run: |
          ln -s /usr/bin/python3.9 /github/workspace/python3.9  
      - name: Install dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d 
      - name: Python build
        # env:
        #   _file_changes: ${{ steps.file_changes.outputs.files }}
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run build
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add .
          git diff-index --quiet HEAD || (git commit -m "Auto Commit" -a --no-verify)
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # branch: ${{ github.ref }}
          branch: refs/heads/main
